'use strict'

module.exports = [
  { name: 'adcodes' },
  { name: 'addresses' },
  { name: 'affiliates' },
  { name: 'attribute_groups' },
  { name: 'attributes' },
  { name: 'blog_categories' },
  { name: 'blog_posts', collect: 'posts' },
  { name: 'blogs' },
  { name: 'cart_items' },
  { name: 'carts' },
  { name: 'categories' },
  { name: 'coupon_codes' },
  { name: 'credit_cards' },
  { name: 'custom_field_values', collect: 'values' },
  { name: 'custom_fields' },
  { name: 'custom_shipping_methods' },
  { name: 'customer_payment_methods' },
  { name: 'customer_types' },
  { name: 'customers' },
  { name: 'discount_methods' },
  { name: 'discount_rules' },
  { name: 'drips' },
  { name: 'email_templates' },
  { name: 'gift_certificate_transactions', collect: 'transactions' },
  { name: 'gift_certificates' },
  // { name: 'inventory' },
  { name: 'links' },
  { name: 'mailing_lists' },
  { name: 'manufacturers' },
  { name: 'order_addresses', collect: 'addresses' },
  { name: 'order_items', collect: 'items' },
  { name: 'order_payments', collect: 'payments' },
  { name: 'order_shipments', collect: 'shipments' },
  { name: 'order_statuses' },
  { name: 'orders' },
  { name: 'pages' },
  { name: 'payment_methods' },
  { name: 'price_calculator_rule_modifiers' },
  { name: 'price_calculator_rules' },
  { name: 'price_calculators', collect: 'price_calculation' },
  { name: 'product_lists' },
  { name: 'product_pictures', collect: 'pictures' },
  { name: 'product_reviews' },
  { name: 'product_statuses' },
  { name: 'product_variants', collect: 'variants' },
  { name: 'products' },
  { name: 'profiles' },
  { name: 'quotes' },
  { name: 'regions' },
  { name: 'sessions' },
  { name: 'shipping_providers' },
  { name: 'shipping_rate_adjustments' },
  { name: 'stores' },
  { name: 'subscriptions' },
  { name: 'tax_rates' },
  { name: 'url_redirects' },
  { name: 'users' },
  { name: 'variant_groups' },
  { name: 'variant_inventory' },
  { name: 'warehouses' },
  { name: 'wishlists' }
]
